/**
 * Integration tests against REAL Playwright artifacts.
 *
 * The fixtures in tests/fixtures/real/ were generated by running the tiny
 * self-contained Playwright project in tests/fixtures/playwright-project
 * with genuine @playwright/test versions (see tests/fixtures/real/README.md):
 *
 * - real/modern/  → @playwright/test 1.61 (template-embedded base64 report)
 * - real/v1.40/   → @playwright/test 1.40 (window.playwrightReportBase64 script form)
 *
 * They are checked in verbatim — NOT hand-crafted — so these tests exercise
 * the exact NDJSON trace format (test.trace with before/after event pairs)
 * and the base64-zip HTML report format that Playwright actually produces.
 */
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, afterEach } from 'vitest';
import JSZip from 'jszip';
import { processTraceFile } from '../../src/processors/trace-file.js';
import { processHtmlReport } from '../../src/processors/html-report.js';
import type { SanitizerConfig, RemoveRule } from '../../src/config/types.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(HERE, '..', 'fixtures', 'real');

const SPINNER_RULE: RemoveRule[] = [
  { label: 'spinner-noise', stepName: /waitForSpinnerToDisappear/ },
];

let tmpDir: string;
function stage(fixturePath: string): string {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'real-artifacts-'));
  const dest = path.join(tmpDir, path.basename(fixturePath));
  fs.copyFileSync(fixturePath, dest);
  return dest;
}

afterEach(() => {
  if (tmpDir && fs.existsSync(tmpDir)) {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// Trace helpers
// ---------------------------------------------------------------------------

interface TraceLine {
  type?: string;
  callId?: string;
  stepId?: string;
  parentId?: string;
  title?: string;
  /** Pre-1.45 name for the step title. */
  apiName?: string;
  startTime?: number;
  endTime?: number;
  version?: number;
  [key: string]: unknown;
}

/** Step display title across Playwright versions (title in modern, apiName in 1.40). */
function titleOf(l: TraceLine): string | undefined {
  return l.title ?? l.apiName;
}

async function readTraceLines(zipPath: string): Promise<TraceLine[]> {
  const zip = await JSZip.loadAsync(fs.readFileSync(zipPath));
  const entry = zip.file('test.trace');
  expect(entry, 'test.trace must exist in the trace zip').not.toBeNull();
  const content = await entry!.async('string');
  return content
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => JSON.parse(l) as TraceLine);
}

/** Returns callIds of before-events that have no paired after-event. */
function unpairedBefores(lines: TraceLine[]): Set<string> {
  const befores = new Set<string>();
  const afters = new Set<string>();
  for (const l of lines) {
    const id = l.callId ?? l.stepId;
    if (!id) continue;
    if (l.type === 'before') befores.add(id);
    else if (l.type === 'after') afters.add(id);
  }
  return new Set([...befores].filter((id) => !afters.has(id)));
}

/**
 * Asserts the structural invariants the Playwright trace viewer relies on
 * when loading a trace via `npx playwright show-trace`:
 *
 * - every line is valid JSON (checked implicitly by readTraceLines)
 * - the context-options header line survives untouched
 * - every "after" event pairs with a preceding "before" (same callId)
 * - sanitization creates no NEW unpaired "before" events (real Playwright
 *   traces may legitimately contain one — e.g. a still-open "After Hooks"
 *   step in 1.40-era traces — so pre-existing unpaired ids are allowed via
 *   `allowedUnpaired`)
 * - every parentId references an existing step's callId (no dangling parents)
 * - per-step startTime <= endTime, and child spans nest within repaired
 *   parent spans (monotonic timeline)
 */
function assertTraceViewerCompatible(
  lines: TraceLine[],
  allowedUnpaired: Set<string> = new Set()
): void {
  // Header line intact (modern traces start with a context-options event;
  // 1.40-era test traces have no header line)
  const header = lines[0]!;
  if (header.type === 'context-options') {
    expect(header.version).toBeTypeOf('number');
  } else {
    expect(header.type).toBe('before');
  }

  const befores = new Map<string, TraceLine>();
  const afters = new Map<string, TraceLine>();

  for (const line of lines) {
    if (line.type === 'before') {
      const id = line.callId ?? line.stepId;
      expect(id, 'before event must have a callId').toBeTruthy();
      befores.set(id!, line);
    } else if (line.type === 'after') {
      const id = line.callId ?? line.stepId;
      expect(id, 'after event must have a callId').toBeTruthy();
      expect(
        befores.has(id!),
        `after event ${id} must have a matching before event earlier in the stream`
      ).toBe(true);
      afters.set(id!, line);
    }
  }

  // Every before has its paired after, except ids that were already unpaired
  // in the original artifact (no NEW half-open steps introduced)
  for (const [id] of befores) {
    if (!afters.has(id)) {
      expect(
        allowedUnpaired.has(id),
        `before event ${id} lost its paired after event`
      ).toBe(true);
    }
  }

  // No dangling parents, and child spans nest within parent spans
  for (const [id, before] of befores) {
    if (before.parentId) {
      expect(
        befores.has(before.parentId),
        `step ${id} references missing parent ${before.parentId}`
      ).toBe(true);

      const parentBefore = befores.get(before.parentId)!;
      const parentAfter = afters.get(before.parentId);
      const after = afters.get(id);
      expect(before.startTime!).toBeGreaterThanOrEqual(parentBefore.startTime! - 0.001);
      if (after && parentAfter) {
        expect(after.endTime!).toBeLessThanOrEqual(parentAfter.endTime! + 0.001);
      }
    }

    const after = afters.get(id);
    if (after) {
      expect(after.endTime!).toBeGreaterThanOrEqual(before.startTime!);
    }
  }
}

/** Returns before-events in stream order (the flat step list). */
function beforeEvents(lines: TraceLine[]): TraceLine[] {
  return lines.filter((l) => l.type === 'before');
}

// ---------------------------------------------------------------------------
// Trace tests (run against both real fixture generations)
// ---------------------------------------------------------------------------

for (const generation of ['modern', 'v1.40'] as const) {
  const traceFixture = path.join(FIXTURES, generation, 'trace.zip');

  describe(`real trace.zip [${generation}]`, () => {
    it('fixture is genuine: NDJSON test.trace with before/after step events', async () => {
      const lines = await readTraceLines(traceFixture);
      assertTraceViewerCompatible(lines, unpairedBefores(lines));

      const spinnerSteps = beforeEvents(lines).filter((l) =>
        titleOf(l)?.includes('waitForSpinnerToDisappear')
      );
      expect(spinnerSteps.length).toBeGreaterThan(0);
      // The fixture nests children under the spinner steps
      const spinnerIds = new Set(spinnerSteps.map((s) => s.callId));
      const children = beforeEvents(lines).filter(
        (l) => l.parentId && spinnerIds.has(l.parentId)
      );
      expect(children.length).toBeGreaterThan(0);
    });

    it('keep-shell: removes descendant events, keeps the matched step, stays viewer-compatible', async () => {
      const original = await readTraceLines(traceFixture);
      const originalSpinnerIds = new Set(
        beforeEvents(original)
          .filter((l) => titleOf(l)?.includes('waitForSpinnerToDisappear'))
          .map((l) => l.callId!)
      );
      // Full descendant set (children can nest — walk transitively)
      const descendants = new Set<string>();
      let grew = true;
      while (grew) {
        grew = false;
        for (const l of beforeEvents(original)) {
          if (
            l.parentId &&
            (originalSpinnerIds.has(l.parentId) || descendants.has(l.parentId)) &&
            !descendants.has(l.callId!)
          ) {
            descendants.add(l.callId!);
            grew = true;
          }
        }
      }
      expect(descendants.size).toBeGreaterThan(0);

      const zipPath = stage(traceFixture);
      const config: SanitizerConfig = {
        output: { mode: 'in-place' },
        remove: { orphanStrategy: 'keep-shell' },
      };

      const result = await processTraceFile(zipPath, zipPath, config, [], SPINNER_RULE);

      // (3) summary counts are non-zero
      expect(result.stepsRemoved).toBeGreaterThan(0);
      expect(result.stepsRemoved).toBe(descendants.size);
      expect(result.removalMatches.length).toBeGreaterThan(0);

      const sanitized = await readTraceLines(zipPath);

      // Matched parent steps remain (shell kept: both before and after events)
      for (const id of originalSpinnerIds) {
        expect(sanitized.some((l) => l.type === 'before' && l.callId === id)).toBe(true);
        expect(sanitized.some((l) => l.type === 'after' && l.callId === id)).toBe(true);
      }

      // All descendant events are gone (before, after, and any other event lines)
      for (const id of descendants) {
        expect(
          sanitized.some((l) => (l.callId ?? l.stepId) === id),
          `descendant ${id} should have been removed`
        ).toBe(false);
      }

      // Unrelated steps survive untouched
      const survivingTitles = beforeEvents(sanitized).map((l) => titleOf(l));
      expect(survivingTitles).toContain('open login page');
      expect(survivingTitles).toContain('fill credentials');
      expect(survivingTitles).toContain('assert dashboard');

      // (1) trace still opens in the viewer: structural invariants hold
      assertTraceViewerCompatible(sanitized, unpairedBefores(original));

      // Line order of untouched events is preserved
      const originalOrder = original
        .filter((l) => !descendants.has((l.callId ?? l.stepId) as string))
        .map((l) => `${l.type}:${l.callId ?? l.stepId ?? ''}`);
      const sanitizedOrder = sanitized.map((l) => `${l.type}:${l.callId ?? l.stepId ?? ''}`);
      expect(sanitizedOrder).toEqual(originalOrder);
    });

    it('remove-children: removes the matched step and its whole subtree', async () => {
      const original = await readTraceLines(traceFixture);
      const zipPath = stage(traceFixture);
      const config: SanitizerConfig = {
        output: { mode: 'in-place' },
        remove: { orphanStrategy: 'remove-children' },
      };

      const result = await processTraceFile(zipPath, zipPath, config, [], SPINNER_RULE);
      expect(result.stepsRemoved).toBeGreaterThan(0);

      const sanitized = await readTraceLines(zipPath);
      expect(
        sanitized.some((l) => titleOf(l)?.includes('waitForSpinnerToDisappear'))
      ).toBe(false);
      assertTraceViewerCompatible(sanitized, unpairedBefores(original));
    });

    it('keeps timestamps monotonic after absorb-into-prev repair', async () => {
      const original = await readTraceLines(traceFixture);
      const zipPath = stage(traceFixture);
      const config: SanitizerConfig = {
        output: { mode: 'in-place' },
        remove: {
          orphanStrategy: 'remove-children',
          timestampStrategy: 'absorb-into-prev',
        },
      };

      await processTraceFile(zipPath, zipPath, config, [], SPINNER_RULE);
      const sanitized = await readTraceLines(zipPath);
      assertTraceViewerCompatible(sanitized, unpairedBefores(original));

      // Top-level (parentless) steps must remain in non-decreasing start order
      const topLevel = beforeEvents(sanitized).filter((l) => !l.parentId);
      for (let i = 1; i < topLevel.length; i++) {
        expect(topLevel[i]!.startTime!).toBeGreaterThanOrEqual(
          topLevel[i - 1]!.startTime!
        );
      }
    });
  });
}

// ---------------------------------------------------------------------------
// HTML report helpers
// ---------------------------------------------------------------------------

interface ShardStep {
  title?: string;
  startTime?: string;
  duration?: number;
  count?: number;
  steps?: ShardStep[];
  [key: string]: unknown;
}

const WINDOW_RE =
  /window\.playwrightReportBase64\s*=\s*"data:application\/zip;base64,([A-Za-z0-9+/=]*)";/;
const TEMPLATE_RE =
  /<template id="playwrightReportBase64">data:application\/zip;base64,([^<]*)<\/template>/;

async function decodeReport(htmlPath: string): Promise<{
  zip: JSZip;
  shards: Array<{ name: string; data: { tests: Array<{ results: Array<{ steps: ShardStep[] }> }> } }>;
  reportJson: unknown;
}> {
  const html = fs.readFileSync(htmlPath, 'utf-8');
  const m = WINDOW_RE.exec(html) ?? TEMPLATE_RE.exec(html);
  expect(m, 'report must embed a base64 zip payload').not.toBeNull();

  // (2) base64 round-trip must be a byte-valid zip
  const zip = await JSZip.loadAsync(Buffer.from(m![1]!, 'base64'));
  const reportEntry = zip.file('report.json');
  expect(reportEntry, 'report.json must exist in the payload zip').not.toBeNull();
  const reportJson = JSON.parse(await reportEntry!.async('string'));

  const shards: Array<{
    name: string;
    data: { tests: Array<{ results: Array<{ steps: ShardStep[] }> }> };
  }> = [];
  const names: string[] = [];
  zip.forEach((rel, entry) => {
    if (!entry.dir && rel.endsWith('.json') && rel !== 'report.json') names.push(rel);
  });
  for (const name of names) {
    const data = JSON.parse(await zip.file(name)!.async('string'));
    shards.push({ name, data });
  }
  expect(shards.length).toBeGreaterThan(0);
  return { zip, shards, reportJson };
}

function flattenSteps(steps: ShardStep[] | undefined, out: ShardStep[] = []): ShardStep[] {
  for (const s of steps ?? []) {
    out.push(s);
    flattenSteps(s.steps, out);
  }
  return out;
}

function allShardSteps(shards: Awaited<ReturnType<typeof decodeReport>>['shards']): ShardStep[] {
  const out: ShardStep[] = [];
  for (const shard of shards) {
    for (const test of shard.data.tests ?? []) {
      for (const res of test.results ?? []) {
        flattenSteps(res.steps, out);
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// HTML report tests (both embedding styles)
// ---------------------------------------------------------------------------

for (const generation of ['modern', 'v1.40'] as const) {
  const htmlFixture = path.join(FIXTURES, generation, 'index.html');

  describe(`real HTML report [${generation}]`, () => {
    it('fixture is genuine: embedded base64 zip with report.json + shards containing step trees', async () => {
      const { shards } = await decodeReport(htmlFixture);
      const steps = allShardSteps(shards);
      const spinner = steps.filter((s) => s.title?.includes('waitForSpinnerToDisappear'));
      expect(spinner.length).toBeGreaterThan(0);
      expect(spinner.some((s) => (s.steps?.length ?? 0) > 0)).toBe(true);
    });

    it('keep-shell: matched step kept with emptied children; report round-trips as valid zip', async () => {
      const htmlPath = stage(htmlFixture);
      const config: SanitizerConfig = {
        output: { mode: 'in-place' },
        remove: { orphanStrategy: 'keep-shell' },
      };

      const result = await processHtmlReport(htmlPath, htmlPath, config, [], SPINNER_RULE);

      // (3) summary counts are non-zero
      expect(result.stepsRemoved).toBeGreaterThan(0);
      expect(result.removalMatches.length).toBeGreaterThan(0);

      // (2) sanitized HTML still renders: payload decodes as a byte-valid zip
      const { shards, reportJson } = await decodeReport(htmlPath);
      expect(reportJson).toBeTruthy();

      const steps = allShardSteps(shards);
      const spinner = steps.filter((s) => s.title?.includes('waitForSpinnerToDisappear'));
      expect(spinner.length).toBeGreaterThan(0);
      for (const s of spinner) {
        expect(s.steps).toEqual([]);
        if (typeof s.count === 'number') expect(s.count).toBe(1);
      }

      // Former children are gone from the tree entirely
      expect(steps.some((s) => s.title === 'check spinner visible')).toBe(false);
      expect(steps.some((s) => s.title === 'inner poll tick')).toBe(false);

      // Unrelated steps survive
      expect(steps.some((s) => s.title === 'open login page')).toBe(true);
    });

    it('remove-children: matched subtree removed, sibling timestamps stay monotonic', async () => {
      const htmlPath = stage(htmlFixture);
      const config: SanitizerConfig = {
        output: { mode: 'in-place' },
        remove: {
          orphanStrategy: 'remove-children',
          timestampStrategy: 'absorb-into-prev',
        },
      };

      const result = await processHtmlReport(htmlPath, htmlPath, config, [], SPINNER_RULE);
      expect(result.stepsRemoved).toBeGreaterThan(0);

      const { shards } = await decodeReport(htmlPath);
      const steps = allShardSteps(shards);
      expect(steps.some((s) => s.title?.includes('waitForSpinnerToDisappear'))).toBe(false);

      // Sibling startTimes remain non-decreasing after repair
      for (const shard of shards) {
        for (const test of shard.data.tests ?? []) {
          for (const res of test.results ?? []) {
            const siblings = res.steps ?? [];
            for (let i = 1; i < siblings.length; i++) {
              const prev = Date.parse(siblings[i - 1]!.startTime ?? '');
              const cur = Date.parse(siblings[i]!.startTime ?? '');
              if (Number.isFinite(prev) && Number.isFinite(cur)) {
                expect(cur).toBeGreaterThanOrEqual(prev);
              }
            }
          }
        }
      }
    });

    it('preserves the embedding wrapper style when writing back', async () => {
      const htmlPath = stage(htmlFixture);
      const originalHtml = fs.readFileSync(htmlPath, 'utf-8');
      const usesWindowForm = WINDOW_RE.test(originalHtml);

      const config: SanitizerConfig = {
        output: { mode: 'in-place' },
        remove: { orphanStrategy: 'keep-shell' },
      };
      await processHtmlReport(htmlPath, htmlPath, config, [], SPINNER_RULE);

      const newHtml = fs.readFileSync(htmlPath, 'utf-8');
      if (usesWindowForm) {
        expect(WINDOW_RE.test(newHtml)).toBe(true);
      } else {
        expect(TEMPLATE_RE.test(newHtml)).toBe(true);
      }
      // Everything outside the payload is untouched
      const stripPayload = (h: string) =>
        h.replace(WINDOW_RE, 'PAYLOAD').replace(TEMPLATE_RE, 'PAYLOAD');
      expect(stripPayload(newHtml)).toBe(stripPayload(originalHtml));
    });
  });
}
